use_frameworks!

target 'GithubSwiftApi_Example' do
  pod 'GithubSwiftApi', :path => '../'

  target 'GithubSwiftApi_Tests' do
    inherit! :search_paths
    pod 'GithubSwiftApi', :path => '../'
    
  end
end
