name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2


    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_12.1.app

    - name: Install Dependencies
      run: |
        cd GithubSwiftApi
        cd Example
        pod install --repo-update
    - name: Build and test
      run: xcodebuild clean build test -workspace Example/GithubSwiftApi.xcworkspace/ -scheme GithubSwiftApi-Example  -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.1'
    
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.POD_TOKEN }}


